#!/usr/bin/env bash

set -eu
set -o pipefail

usage=$(basename "$0")" [options] <benchmark>"

bench_names="rsg-nhbr-allgather"

num_procs=16

itr=10

frndship_thr=4

exec_root=.

out_root=.

rsg-nhbr-allgather()
{
    rsg-nhbr-coll allgather
}

rsg-nhbr-coll()
{
    local nhbr_coll=$1

    prob_list=( 0.05 0.1 0.2 0.4 0.6 0.8 )

    for p in ${prob_list[@]}; do
        for i in $(seq 10); do
            echo "============ sparsity factor p = $p," \
                 "friendship_thr = $frndship_thr, alg = $alg ============"
            export MPICH_INEIGHBOR_ALLGATHER_INTRA_ALGORITHM=$alg
            export MPICH_NEIGHBOR_COLL_MSG_COMB_FRNDSHP_THRSHLD=$frndship_thr
            mpiexec -n "$num_procs" "$bench_exec" "$p" "$itr" \
            | tee -a "$out_dir/${alg}_p${p}_${num_procs}"
        done
    done
}

while getopts ":hln:o:e:" opt; do
    case $opt in
        h)
            echo $usage
            exit 0
            ;;
        l)
            echo $bench_names
            exit 0
            ;;
        n)
            num_procs=$OPTARG
            ;;
        o)
            out_root=$OPTARG
            ;;
        e)
            exec_root=$OPTARG
            ;;
        \?)
            echo "Invalid option"
            exit 1
            ;;
    esac
done

shift $(($OPTIND-1))

if [ $# -ne 1 ]; then
    echo -e $usage
    exit 1
fi

bench_name=$1
bench_exec=$exec_root/$bench_name
out_dir=$out_root/${bench_name}.out/$num_procs

if [ ! -d "$out_dir" ]; then
    mkdir -p "$out_dir"
fi

for alg in {comb,auto}; do
    $bench_name
done
